import type { CompanyRow } from "./company-types";

export interface CompanyField {
  key: keyof CompanyRow;
  label: string;
  group: string;
  type: "text" | "number" | "percent" | "rating" | "tags" | "json";
}

export const COMPANY_FIELDS: CompanyField[] = [
  // SECTION 1: Company Overview
  { key: "name", label: "Name", group: "Overview", type: "text" },
  { key: "short_name", label: "Short name", group: "Overview", type: "text" },
  { key: "category", label: "Category", group: "Overview", type: "text" },
  { key: "incorporation_year", label: "Incorporation year", group: "Overview", type: "number" },
  { key: "nature_of_company", label: "Nature of company", group: "Overview", type: "text" },
  { key: "headquarters_address", label: "Headquarters", group: "Overview", type: "text" },
  { key: "operating_countries", label: "Operating countries", group: "Overview", type: "tags" },
  { key: "office_count", label: "Office count", group: "Overview", type: "number" },
  { key: "office_locations", label: "Office locations", group: "Overview", type: "tags" },
  { key: "employee_size", label: "Employee size", group: "Overview", type: "text" },
  { key: "overview_text", label: "Overview", group: "Overview", type: "text" },
  { key: "history_timeline", label: "History timeline", group: "Overview", type: "json" },
  { key: "recent_news", label: "Recent news", group: "Overview", type: "json" },

  // SECTION 2: Business & Market
  {
    key: "pain_points_addressed",
    label: "Pain points addressed",
    group: "Business & Market",
    type: "text",
  },
  { key: "focus_sectors", label: "Focus sectors", group: "Business & Market", type: "tags" },
  { key: "offerings_description", label: "Offerings", group: "Business & Market", type: "text" },
  { key: "top_customers", label: "Top customers", group: "Business & Market", type: "tags" },
  {
    key: "core_value_proposition",
    label: "Core value proposition",
    group: "Business & Market",
    type: "text",
  },
  {
    key: "unique_differentiators",
    label: "Unique differentiators",
    group: "Business & Market",
    type: "text",
  },
  {
    key: "competitive_advantages",
    label: "Competitive advantages",
    group: "Business & Market",
    type: "text",
  },
  { key: "weaknesses_gaps", label: "Weaknesses / gaps", group: "Business & Market", type: "text" },
  {
    key: "key_challenges_needs",
    label: "Key challenges & needs",
    group: "Business & Market",
    type: "text",
  },
  { key: "key_competitors", label: "Key competitors", group: "Business & Market", type: "tags" },
  { key: "tam", label: "TAM", group: "Business & Market", type: "text" },
  { key: "sam", label: "SAM", group: "Business & Market", type: "text" },
  { key: "som", label: "SOM", group: "Business & Market", type: "text" },
  {
    key: "market_share_percentage",
    label: "Market share",
    group: "Business & Market",
    type: "percent",
  },
  {
    key: "go_to_market_strategy",
    label: "Go-to-market strategy",
    group: "Business & Market",
    type: "text",
  },
  {
    key: "strategic_priorities",
    label: "Strategic priorities",
    group: "Business & Market",
    type: "text",
  },
  {
    key: "future_projections",
    label: "Future projections",
    group: "Business & Market",
    type: "text",
  },

  // SECTION 3: Culture, People & Work
  { key: "work_culture_summary", label: "Work culture summary", group: "Culture", type: "text" },
  { key: "hiring_velocity", label: "Hiring velocity", group: "Culture", type: "text" },
  { key: "employee_turnover", label: "Employee turnover", group: "Culture", type: "text" },
  { key: "avg_retention_tenure", label: "Avg retention tenure", group: "Culture", type: "text" },
  { key: "manager_quality", label: "Manager quality", group: "Culture", type: "text" },
  { key: "psychological_safety", label: "Psychological safety", group: "Culture", type: "text" },
  { key: "feedback_culture", label: "Feedback culture", group: "Culture", type: "text" },
  { key: "diversity_metrics", label: "Diversity metrics", group: "Culture", type: "json" },
  { key: "diversity_inclusion_score", label: "D&I score", group: "Culture", type: "rating" },
  { key: "ethical_standards", label: "Ethical standards", group: "Culture", type: "text" },
  { key: "layoff_history", label: "Layoff history", group: "Culture", type: "text" },
  { key: "burnout_risk", label: "Burnout risk", group: "Culture", type: "text" },
  { key: "mission_clarity", label: "Mission clarity", group: "Culture", type: "text" },

  // SECTION 4: Learning, Growth & Career Signal
  { key: "training_spend", label: "Training spend", group: "Learning & Growth", type: "text" },
  {
    key: "onboarding_quality",
    label: "Onboarding quality",
    group: "Learning & Growth",
    type: "text",
  },
  { key: "learning_culture", label: "Learning culture", group: "Learning & Growth", type: "text" },
  { key: "exposure_quality", label: "Exposure quality", group: "Learning & Growth", type: "text" },
  {
    key: "mentorship_availability",
    label: "Mentorship availability",
    group: "Learning & Growth",
    type: "text",
  },
  {
    key: "internal_mobility",
    label: "Internal mobility",
    group: "Learning & Growth",
    type: "text",
  },
  {
    key: "promotion_clarity",
    label: "Promotion clarity",
    group: "Learning & Growth",
    type: "text",
  },
  { key: "tools_access", label: "Tools access", group: "Learning & Growth", type: "text" },
  { key: "role_clarity", label: "Role clarity", group: "Learning & Growth", type: "text" },
  { key: "early_ownership", label: "Early ownership", group: "Learning & Growth", type: "text" },
  { key: "work_impact", label: "Work impact", group: "Learning & Growth", type: "text" },
  {
    key: "execution_thinking_balance",
    label: "Execution / thinking balance",
    group: "Learning & Growth",
    type: "text",
  },
  { key: "automation_level", label: "Automation level", group: "Learning & Growth", type: "text" },
  {
    key: "cross_functional_exposure",
    label: "Cross-functional exposure",
    group: "Learning & Growth",
    type: "text",
  },
  {
    key: "exit_opportunities",
    label: "Exit opportunities",
    group: "Learning & Growth",
    type: "text",
  },
  { key: "skill_relevance", label: "Skill relevance", group: "Learning & Growth", type: "text" },
  { key: "network_strength", label: "Network strength", group: "Learning & Growth", type: "text" },
  { key: "global_exposure", label: "Global exposure", group: "Learning & Growth", type: "text" },
  {
    key: "external_recognition",
    label: "External recognition",
    group: "Learning & Growth",
    type: "text",
  },

  // SECTION 5: Compensation & Lifestyle
  {
    key: "fixed_vs_variable_pay",
    label: "Fixed vs variable pay",
    group: "Compensation",
    type: "text",
  },
  {
    key: "bonus_predictability",
    label: "Bonus predictability",
    group: "Compensation",
    type: "text",
  },
  { key: "esops_incentives", label: "ESOPs / incentives", group: "Compensation", type: "text" },
  {
    key: "family_health_insurance",
    label: "Family health insurance",
    group: "Compensation",
    type: "text",
  },
  { key: "relocation_support", label: "Relocation support", group: "Compensation", type: "text" },
  { key: "lifestyle_benefits", label: "Lifestyle benefits", group: "Compensation", type: "text" },
  { key: "leave_policy", label: "Leave policy", group: "Compensation", type: "text" },
  { key: "health_support", label: "Health support", group: "Compensation", type: "text" },

  // SECTION 6: Work Logistics & Safety
  { key: "remote_policy_details", label: "Remote policy", group: "Work Logistics", type: "text" },
  { key: "typical_hours", label: "Typical hours", group: "Work Logistics", type: "text" },
  {
    key: "overtime_expectations",
    label: "Overtime expectations",
    group: "Work Logistics",
    type: "text",
  },
  { key: "weekend_work", label: "Weekend work", group: "Work Logistics", type: "text" },
  { key: "flexibility_level", label: "Flexibility level", group: "Work Logistics", type: "text" },
  {
    key: "location_centrality",
    label: "Location centrality",
    group: "Work Logistics",
    type: "text",
  },
  {
    key: "public_transport_access",
    label: "Public transport access",
    group: "Work Logistics",
    type: "text",
  },
  { key: "cab_policy", label: "Cab policy", group: "Work Logistics", type: "text" },
  {
    key: "airport_commute_time",
    label: "Airport commute time",
    group: "Work Logistics",
    type: "text",
  },
  { key: "office_zone_type", label: "Office zone type", group: "Work Logistics", type: "text" },
  { key: "area_safety", label: "Area safety", group: "Work Logistics", type: "text" },
  { key: "safety_policies", label: "Safety policies", group: "Work Logistics", type: "text" },
  {
    key: "infrastructure_safety",
    label: "Infrastructure safety",
    group: "Work Logistics",
    type: "text",
  },
  {
    key: "emergency_preparedness",
    label: "Emergency preparedness",
    group: "Work Logistics",
    type: "text",
  },

  // SECTION 7: Financials, Risk & Stability
  { key: "annual_revenue", label: "Annual revenue", group: "Financials", type: "text" },
  { key: "annual_profit", label: "Annual profit", group: "Financials", type: "text" },
  { key: "revenue_mix", label: "Revenue mix", group: "Financials", type: "json" },
  { key: "valuation", label: "Valuation", group: "Financials", type: "text" },
  { key: "yoy_growth_rate", label: "YoY growth", group: "Financials", type: "percent" },
  { key: "profitability_status", label: "Profitability", group: "Financials", type: "text" },
  { key: "key_investors", label: "Key investors", group: "Financials", type: "tags" },
  {
    key: "recent_funding_rounds",
    label: "Recent funding rounds",
    group: "Financials",
    type: "json",
  },
  { key: "total_capital_raised", label: "Total capital raised", group: "Financials", type: "text" },
  { key: "burn_rate", label: "Burn rate", group: "Financials", type: "text" },
  { key: "runway_months", label: "Runway (months)", group: "Financials", type: "number" },
  { key: "burn_multiplier", label: "Burn multiplier", group: "Financials", type: "rating" },
  { key: "esg_ratings", label: "ESG ratings", group: "Financials", type: "text" },
  { key: "regulatory_status", label: "Regulatory status", group: "Financials", type: "text" },
  { key: "legal_issues", label: "Legal issues", group: "Financials", type: "text" },
  {
    key: "supply_chain_dependencies",
    label: "Supply chain dependencies",
    group: "Financials",
    type: "text",
  },
  { key: "geopolitical_risks", label: "Geopolitical risks", group: "Financials", type: "text" },
  { key: "macro_risks", label: "Macro risks", group: "Financials", type: "text" },

  // SECTION 8: Technology & Innovation
  { key: "tech_stack", label: "Tech stack", group: "Technology", type: "tags" },
  { key: "technology_partners", label: "Technology partners", group: "Technology", type: "tags" },
  {
    key: "intellectual_property",
    label: "Intellectual property",
    group: "Technology",
    type: "text",
  },
  { key: "r_and_d_investment", label: "R&D investment", group: "Technology", type: "text" },
  { key: "ai_ml_adoption_level", label: "AI/ML adoption level", group: "Technology", type: "text" },
  {
    key: "cybersecurity_posture",
    label: "Cybersecurity posture",
    group: "Technology",
    type: "text",
  },
  { key: "innovation_roadmap", label: "Innovation roadmap", group: "Technology", type: "text" },
  { key: "product_pipeline", label: "Product pipeline", group: "Technology", type: "text" },
  {
    key: "tech_adoption_rating",
    label: "Tech adoption rating",
    group: "Technology",
    type: "rating",
  },
  {
    key: "partnership_ecosystem",
    label: "Partnership ecosystem",
    group: "Technology",
    type: "text",
  },

  // SECTION 9: Leadership & Contacts
  { key: "ceo_name", label: "CEO", group: "Leadership", type: "text" },
  { key: "key_leaders", label: "Key leaders", group: "Leadership", type: "json" },
  { key: "board_members", label: "Board members", group: "Leadership", type: "json" },
  { key: "warm_intro_pathways", label: "Warm intro pathways", group: "Leadership", type: "text" },
  {
    key: "decision_maker_access",
    label: "Decision-maker access",
    group: "Leadership",
    type: "text",
  },
  {
    key: "primary_contact_email",
    label: "Primary contact email",
    group: "Leadership",
    type: "text",
  },
  { key: "primary_phone_number", label: "Primary phone", group: "Leadership", type: "text" },
  { key: "contact_person_name", label: "Contact person name", group: "Leadership", type: "text" },
  { key: "contact_person_title", label: "Contact person title", group: "Leadership", type: "text" },
  { key: "contact_person_email", label: "Contact person email", group: "Leadership", type: "text" },
  { key: "contact_person_phone", label: "Contact person phone", group: "Leadership", type: "text" },
  {
    key: "preparation_strategy",
    label: "Preparation Strategy",
    group: "Intelligence",
    type: "text",
  },

  // SECTION 10: Brand & Digital Presence
  { key: "website_url", label: "Website", group: "Brand", type: "text" },
  { key: "website_quality", label: "Website quality", group: "Brand", type: "text" },
  { key: "website_rating", label: "Website rating", group: "Brand", type: "rating" },
  { key: "website_traffic_rank", label: "Traffic rank", group: "Brand", type: "text" },
  { key: "social_media_followers", label: "Social media followers", group: "Brand", type: "json" },
  { key: "glassdoor_rating", label: "Glassdoor rating", group: "Brand", type: "rating" },
  { key: "indeed_rating", label: "Indeed rating", group: "Brand", type: "rating" },
  { key: "google_rating", label: "Google rating", group: "Brand", type: "rating" },
  { key: "linkedin_url", label: "LinkedIn", group: "Brand", type: "text" },
  { key: "twitter_handle", label: "Twitter handle", group: "Brand", type: "text" },
  { key: "facebook_url", label: "Facebook", group: "Brand", type: "text" },
  { key: "instagram_url", label: "Instagram", group: "Brand", type: "text" },
  { key: "marketing_video_url", label: "Marketing video", group: "Brand", type: "text" },
  { key: "customer_testimonials", label: "Customer testimonials", group: "Brand", type: "json" },
  { key: "awards_recognitions", label: "Awards & recognitions", group: "Brand", type: "tags" },
  { key: "brand_sentiment_score", label: "Brand sentiment score", group: "Brand", type: "rating" },
  { key: "event_participation", label: "Event participation", group: "Brand", type: "text" },
  { key: "brand_value", label: "Brand value", group: "Brand", type: "text" },
  { key: "job_description", label: "Job Description", group: "Intelligence", type: "text" },
];
