# Frontend production image
FROM node:20-alpine AS build
WORKDIR /usr/src/app

COPY package.json .
COPY tsconfig.json .
COPY vite.config.ts .
COPY bun.lockb .
COPY bunfig.toml .

RUN npm install

COPY . .
RUN npm run build

FROM nginx:1.26-alpine AS runtime
COPY --from=build /usr/src/app/dist/client /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
