import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import {
  BulletQualityPanel,
  ResumeKeywordAnalyticsPanel,
  ResumeOptimizerOverview,
  ResumeOptimizerUploadPanel,
  ResumeProfilePanel,
  ResumeScoreBreakdownPanel,
  ResumeSuggestionsPanel,
  RoleCompatibilityPanel,
  TargetRolePanel,
} from "@/components/resume-optimizer/ResumeOptimizerPanels";
import { useResumeOptimizerAnalysis } from "@/hooks/use-resume-optimizer";
import {
  downloadResumeOptimizerReport,
  type ResumeOptimizerAnalysis,
} from "@/services/resumeOptimizerService";

export const Route = createFileRoute("/resume-optimizer")({
  head: () => ({
    meta: [
      { title: "Resume ATS Optimizer · PES Placement Intelligence" },
      {
        name: "description",
        content:
          "ATS resume scoring, role compatibility, missing keywords, bullet quality and improvement suggestions.",
      },
    ],
  }),
  component: ResumeOptimizerPage,
});

function ResumeOptimizerPage() {
  const [analysis, setAnalysis] = useState<ResumeOptimizerAnalysis | null>(null);
  const [lastFile, setLastFile] = useState<File | null>(null);
  const [selectedRole, setSelectedRole] = useState("Full Stack Developer");
  const [customRole, setCustomRole] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [downloadStatus, setDownloadStatus] = useState<string | null>(null);
  const [downloadError, setDownloadError] = useState<string | null>(null);
  const optimizer = useResumeOptimizerAnalysis();

  const handleUpload = async (file: File) => {
    setLastFile(file);
    await analyzeFile(file, selectedRole === "Custom Role" ? customRole : selectedRole);
  };

  const analyzeFile = async (file: File, role: string) => {
    setError(null);
    setDownloadStatus(null);
    setDownloadError(null);
    try {
      const result = await optimizer.mutateAsync({ file, targetRole: role });
      setAnalysis(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unable to analyze resume.");
    }
  };

  const handleRoleChange = async (role: string) => {
    setSelectedRole(role);
    setDownloadStatus(null);
    setDownloadError(null);
    if (role !== "Custom Role" && lastFile) {
      await analyzeFile(lastFile, role);
    }
  };

  const handleApplyCustomRole = async () => {
    if (!lastFile || !customRole.trim()) return;
    await analyzeFile(lastFile, customRole.trim());
  };

  const handleDownload = async () => {
    if (!analysis) return;
    setDownloadStatus(null);
    setDownloadError(null);
    try {
      const { blob, filename } = await downloadResumeOptimizerReport(analysis);
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = filename;
      document.body.appendChild(link);
      link.click();
      link.remove();
      URL.revokeObjectURL(url);
      setDownloadStatus(`${filename} was generated by the backend and download was started.`);
    } catch (err) {
      setDownloadError(err instanceof Error ? err.message : "Unable to download report.");
    }
  };

  return (
    <div className="mx-auto max-w-screen-2xl px-4 py-8 sm:px-6">
      <ResumeOptimizerUploadPanel
        loading={optimizer.isPending}
        error={error}
        onUpload={handleUpload}
      />

      <ResumeOptimizerOverview
        analysis={analysis}
        loading={optimizer.isPending}
        downloadStatus={downloadStatus}
        downloadError={downloadError}
        onDownload={handleDownload}
      />
      {analysis && (
        <TargetRolePanel
          selectedRole={selectedRole}
          customRole={customRole}
          loading={optimizer.isPending}
          onRoleChange={handleRoleChange}
          onCustomRoleChange={setCustomRole}
          onApplyCustomRole={handleApplyCustomRole}
        />
      )}
      <ResumeProfilePanel analysis={analysis} />

      {analysis && (
        <>
          <div className="mt-8 grid gap-6 xl:grid-cols-[minmax(320px,0.85fr)_minmax(0,1.15fr)]">
            <ResumeScoreBreakdownPanel analysis={analysis} />
            <RoleCompatibilityPanel analysis={analysis} />
          </div>

          <div className="mt-8 grid gap-6 xl:grid-cols-[minmax(0,1.05fr)_minmax(0,0.95fr)]">
            <ResumeKeywordAnalyticsPanel analysis={analysis} />
            <ResumeSuggestionsPanel analysis={analysis} />
          </div>

          <div className="mt-8">
            <BulletQualityPanel analysis={analysis} />
          </div>
        </>
      )}
    </div>
  );
}
