/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillMappingRouteImport } from './routes/skill-mapping'
import { Route as InnovxRouteImport } from './routes/innovx'
import { Route as HiringProcessRouteImport } from './routes/hiring-process'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyCompanyIdRouteImport } from './routes/company.$companyId'

const SkillMappingRoute = SkillMappingRouteImport.update({
  id: '/skill-mapping',
  path: '/skill-mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovxRoute = InnovxRouteImport.update({
  id: '/innovx',
  path: '/innovx',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringProcessRoute = HiringProcessRouteImport.update({
  id: '/hiring-process',
  path: '/hiring-process',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCompanyIdRoute = CompanyCompanyIdRouteImport.update({
  id: '/company/$companyId',
  path: '/company/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/categories': typeof CategoriesRoute
  '/compare': typeof CompareRoute
  '/explore': typeof ExploreRoute
  '/hiring-process': typeof HiringProcessRoute
  '/innovx': typeof InnovxRoute
  '/skill-mapping': typeof SkillMappingRoute
  '/company/$companyId': typeof CompanyCompanyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/categories': typeof CategoriesRoute
  '/compare': typeof CompareRoute
  '/explore': typeof ExploreRoute
  '/hiring-process': typeof HiringProcessRoute
  '/innovx': typeof InnovxRoute
  '/skill-mapping': typeof SkillMappingRoute
  '/company/$companyId': typeof CompanyCompanyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/categories': typeof CategoriesRoute
  '/compare': typeof CompareRoute
  '/explore': typeof ExploreRoute
  '/hiring-process': typeof HiringProcessRoute
  '/innovx': typeof InnovxRoute
  '/skill-mapping': typeof SkillMappingRoute
  '/company/$companyId': typeof CompanyCompanyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/categories'
    | '/compare'
    | '/explore'
    | '/hiring-process'
    | '/innovx'
    | '/skill-mapping'
    | '/company/$companyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/categories'
    | '/compare'
    | '/explore'
    | '/hiring-process'
    | '/innovx'
    | '/skill-mapping'
    | '/company/$companyId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/categories'
    | '/compare'
    | '/explore'
    | '/hiring-process'
    | '/innovx'
    | '/skill-mapping'
    | '/company/$companyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CategoriesRoute: typeof CategoriesRoute
  CompareRoute: typeof CompareRoute
  ExploreRoute: typeof ExploreRoute
  HiringProcessRoute: typeof HiringProcessRoute
  InnovxRoute: typeof InnovxRoute
  SkillMappingRoute: typeof SkillMappingRoute
  CompanyCompanyIdRoute: typeof CompanyCompanyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skill-mapping': {
      id: '/skill-mapping'
      path: '/skill-mapping'
      fullPath: '/skill-mapping'
      preLoaderRoute: typeof SkillMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovx': {
      id: '/innovx'
      path: '/innovx'
      fullPath: '/innovx'
      preLoaderRoute: typeof InnovxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring-process': {
      id: '/hiring-process'
      path: '/hiring-process'
      fullPath: '/hiring-process'
      preLoaderRoute: typeof HiringProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$companyId': {
      id: '/company/$companyId'
      path: '/company/$companyId'
      fullPath: '/company/$companyId'
      preLoaderRoute: typeof CompanyCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CategoriesRoute: CategoriesRoute,
  CompareRoute: CompareRoute,
  ExploreRoute: ExploreRoute,
  HiringProcessRoute: HiringProcessRoute,
  InnovxRoute: InnovxRoute,
  SkillMappingRoute: SkillMappingRoute,
  CompanyCompanyIdRoute: CompanyCompanyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
