-- Hiring Process Intelligence
-- Stores company-specific hiring round pipelines without changing the existing company schema.

CREATE TABLE IF NOT EXISTS public.company_hiring_rounds (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id INTEGER NOT NULL,
  round_order INTEGER NOT NULL,
  round_name TEXT NOT NULL,
  round_type TEXT,
  description TEXT,
  difficulty_level TEXT,
  elimination_rate TEXT,
  preparation_focus TEXT,
  tips TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT company_hiring_rounds_company_id_fkey
    FOREIGN KEY (company_id)
    REFERENCES public.companies(company_id)
    ON DELETE CASCADE,
  CONSTRAINT company_hiring_rounds_round_order_positive
    CHECK (round_order > 0)
);

CREATE INDEX IF NOT EXISTS idx_company_hiring_rounds_company_id
  ON public.company_hiring_rounds(company_id);

CREATE INDEX IF NOT EXISTS idx_company_hiring_rounds_company_order
  ON public.company_hiring_rounds(company_id, round_order);

CREATE INDEX IF NOT EXISTS idx_company_hiring_rounds_difficulty
  ON public.company_hiring_rounds(difficulty_level);

ALTER TABLE public.company_hiring_rounds ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read company hiring rounds"
  ON public.company_hiring_rounds
  FOR SELECT
  USING (true);
