# 6-Level Coding Arena Question Database
# Curated list of 90 premium MCQ questions + 12 High-Yield Algorithmic Coding Challenges

MCQ_DATA = {
    1: [ # Level 1: Foundational (Arrays & Strings)
        {"id": "l1_01", "topic": "Arrays", "text": "What is the worst-case time complexity of inserting an element at the beginning of an array of size N (without pre-allocated spare space)?", "options": ["O(1)", "O(log N)", "O(N) - requiring shifting all elements", "O(N^2)"], "correct_index": 2, "benchmark_seconds": 30, "explanation": "To insert at index 0, every existing element must be shifted right by one slot, which takes linear O(N) time."},
        {"id": "l1_02", "topic": "Strings", "text": "In a mutable string implementation, what is the best complexity to append a character if spare capacity exists?", "options": ["O(1) amortized", "O(log N)", "O(N)", "O(N log N)"], "correct_index": 0, "benchmark_seconds": 25, "explanation": "If spare capacity already exists, appending is a simple index assignment taking constant O(1) time."},
        {"id": "l1_03", "topic": "Sliding Window", "text": "Which technique is optimal to check for a continuous subarray of size K matching a specific sum?", "options": ["Brute force loops O(N^2)", "Sliding Window O(N)", "Binary Search O(N log N)", "Hashing O(N^2)"], "correct_index": 1, "benchmark_seconds": 30, "explanation": "Maintaining a sliding sum of size K takes linear O(N) time, avoiding redundant additions."},
        {"id": "l1_04", "topic": "Hashing", "text": "Which hash table operations are expected to execute in average constant O(1) time?", "options": ["Lookup, Insertion, Deletion", "Lookup and Sorting", "In-order traversal", "Range minimum queries"], "correct_index": 0, "benchmark_seconds": 25, "explanation": "Standard hash maps perform keys lookup, insertion, and eviction in constant O(1) time on average."},
        {"id": "l1_05", "topic": "Arrays", "text": "What is the spatial complexity of in-place array reversing?", "options": ["O(1) - constant auxiliary memory", "O(log N)", "O(N)", "O(N^2)"], "correct_index": 0, "benchmark_seconds": 20, "explanation": "Reversing in-place only requires swapping elements at symmetric indices using a single temporary variable, taking O(1) space."},
        {"id": "l1_06", "topic": "Strings", "text": "Which operation finds the length of a null-terminated string in C?", "options": ["strlen() - O(N)", "sizeof() - O(1)", "count() - O(log N)", "len() - O(N^2)"], "correct_index": 0, "benchmark_seconds": 25, "explanation": "strlen searches for the null terminator '\\0', scanning N characters in linear O(N) time."},
        {"id": "l1_07", "topic": "Sliding Window", "text": "Which sliding window type adjusts its bounds dynamically based on target constraints?", "options": ["Fixed-size window", "Variable-size window (e.g. dynamic pointers)", "Circular window", "Static block window"], "correct_index": 1, "benchmark_seconds": 30, "explanation": "Variable-size windows shrink or expand their pointers dynamically to meet target constraints (e.g., minimum size matching sum)."},
        {"id": "l1_08", "topic": "Hashing", "text": "In a hash map, what is a collision?", "options": ["Two different keys resolving to the same hash value", "Two identical keys resolving to different hashes", "Exceeding array bounds limits", "Underflow errors"], "correct_index": 0, "benchmark_seconds": 20, "explanation": "A collision occurs when distinct input keys generate identical hash bucket indices."},
        {"id": "l1_09", "topic": "Arrays", "text": "What is the time complexity to access an element at index K in an array?", "options": ["O(1) - direct offset math", "O(log N)", "O(K)", "O(N)"], "correct_index": 0, "benchmark_seconds": 20, "explanation": "Array elements are contiguous. Accessing index K calculates the exact memory offset directly in O(1) constant time."},
        {"id": "l1_10", "topic": "Strings", "text": "Which data structure is optimal to check if two strings are anagrams of each other?", "options": ["Stack", "Queue", "Frequency map / Hash table", "Segment Tree"], "correct_index": 2, "benchmark_seconds": 30, "explanation": "A frequency map tracks character counts. Matching frequency maps for both strings ensures they are anagrams in O(N) time."},
        {"id": "l1_11", "topic": "Arrays", "text": "Which array sorting algorithm is typically used as the primary default library sort in systems (e.g., Timsort)?", "options": ["Bubble Sort", "Selection Sort", "Hybrid Merge/Insertion Sort", "Brute Force"], "correct_index": 2, "benchmark_seconds": 35, "explanation": "Timsort is a stable hybrid sorting algorithm derived from merge sort and insertion sort, highly optimized for real-world datasets."},
        {"id": "l1_12", "topic": "Strings", "text": "How much auxiliary memory does dynamic string concatenation of N characters take in immutable string systems (like Java/Python)?", "options": ["O(1)", "O(log N)", "O(N)", "O(N^2)"], "correct_index": 2, "benchmark_seconds": 30, "explanation": "Concatenation allocates a fresh string copy holding all characters, taking O(N) space."},
        {"id": "l1_13", "topic": "Sliding Window", "text": "What is the window sliding step time complexity when adding one element and evicting one?", "options": ["O(1)", "O(log K)", "O(K)", "O(N)"], "correct_index": 0, "benchmark_seconds": 25, "explanation": "Sliding the window increments bounds and subtracts/adds items in O(1) constant time."},
        {"id": "l1_14", "topic": "Hashing", "text": "What is the worst-case lookup complexity in a hash map with chaining if all elements collide?", "options": ["O(1)", "O(log N)", "O(N) - reduces to a linear list scan", "O(N log N)"], "correct_index": 2, "benchmark_seconds": 25, "explanation": "If all keys hash to the same bucket, they accumulate in a single list, degrading lookups to O(N) linear scan."},
        {"id": "l1_15", "topic": "Arrays", "text": "What is the maximum index of an array of size N in zero-indexed languages?", "options": ["N", "N - 1", "N + 1", "0"], "correct_index": 1, "benchmark_seconds": 15, "explanation": "Zero-indexed arrays start at index 0 and end at index N-1."}
    ],
    2: [ # Level 2: Core Linear Types (Linked Lists, Stacks & Queues)
        {"id": "l2_01", "topic": "Linked Lists", "text": "What is the time complexity of deleting a node at a known pointer location in a doubly linked list?", "options": ["O(1) - updating neighbor pointers", "O(log N)", "O(N)", "O(N^2)"], "correct_index": 0, "benchmark_seconds": 30, "explanation": "With neighbors pointers directly accessible, we can detach the node in constant O(1) time."},
        {"id": "l2_02", "topic": "Stacks & Queues", "text": "Which operation is used to evict an item from a standard FIFO Queue?", "options": ["Pop", "Push", "Enqueue", "Dequeue"], "correct_index": 3, "benchmark_seconds": 20, "explanation": "Dequeue evicts from the front of a FIFO Queue, while Enqueue appends to the rear."},
        {"id": "l2_03", "topic": "Linked Lists", "text": "Which algorithm is optimal to detect a loop/cycle in a singly linked list?", "options": ["Binary Search", "Floyd's Cycle-Finding (Tortoise and Hare)", "Dijkstra's search", "Divide and conquer"], "correct_index": 1, "benchmark_seconds": 35, "explanation": "The slow and fast pointers move at different speeds. If a cycle exists, they will eventually meet, detecting it in O(N) time and O(1) space."},
        {"id": "l2_04", "topic": "Stacks & Queues", "text": "What is the maximum elements retrieval sequence pattern of a Stack?", "options": ["FIFO", "LIFO", "Priority-based", "Random Order"], "correct_index": 1, "benchmark_seconds": 15, "explanation": "Stacks store and retrieve items via the Last In, First Out (LIFO) pattern."},
        {"id": "l2_05", "topic": "Cache Optimization", "text": "Which linked list type is optimal to support Least Recently Used (LRU) evictions?", "options": ["Singly Linked List", "Doubly Linked List - allows immediate O(1) node relocation", "Circular Singly List", "Skip List"], "correct_index": 1, "benchmark_seconds": 40, "explanation": "A doubly linked list allows removing a node and appending it to the head in O(1) constant time."},
        {"id": "l2_06", "topic": "Linked Lists", "text": "What is the worst-case search complexity in a singly linked list of size N?", "options": ["O(1)", "O(log N)", "O(N) - scanning all elements", "O(N^2)"], "correct_index": 2, "benchmark_seconds": 20, "explanation": "Linked lists lack direct indexing; we must traverse from head to tail in O(N) worst-case time."},
        {"id": "l2_07", "topic": "Stacks & Queues", "text": "Which data structure is optimal to implement undo/redo workflows in text editors?", "options": ["Queue", "Two Stacks - pushing and popping edits history", "Binary Tree", "Hash Map"], "correct_index": 1, "benchmark_seconds": 30, "explanation": "Stacks support LIFO, storing changes chronologically. Popping from undo pushes to redo stack, which is highly optimal."},
        {"id": "l2_08", "topic": "Linked Lists", "text": "What is the link update time complexity to merge two circular linked lists of size N and M?", "options": ["O(1) - joining endpoints", "O(log(N+M))", "O(N + M)", "O(N * M)"], "correct_index": 0, "benchmark_seconds": 35, "explanation": "Circular lists hold tail pointers to heads. Swapping tail links merges them instantly in constant O(1) time."},
        {"id": "l2_09", "topic": "Stacks & Queues", "text": "How can you implement a Queue using Stacks?", "options": ["Using a single Stack only", "Using two Stacks - reversing order on demand", "Using a Stack and a Heap", "It is impossible"], "correct_index": 1, "benchmark_seconds": 35, "explanation": "By utilizing an input stack and output stack, we reverse the LIFO order to simulate FIFO in amortized O(1) time."},
        {"id": "l2_10", "topic": "Linked Lists", "text": "What is a major memory disadvantage of Linked Lists compared to Arrays?", "options": ["Pointer storage overhead for every node", "Contiguous allocation limits", "Fixed size constraints", "Constant memory resizing"], "correct_index": 0, "benchmark_seconds": 25, "explanation": "Linked list nodes require additional memory for storing node pointer references alongside values."},
        {"id": "l2_11", "topic": "Stacks & Queues", "text": "Which operation checks the top element of a stack without removing it?", "options": ["Peek", "Pop", "Push", "Clear"], "correct_index": 0, "benchmark_seconds": 15, "explanation": "Peek (or Top) returns the uppermost value of a stack without mutating the stack itself."},
        {"id": "l2_12", "topic": "Linked Lists", "text": "What is the time complexity to locate the middle node of a linked list using slow and fast pointers?", "options": ["O(1)", "O(log N)", "O(N) - single pass traversal", "O(N^2)"], "correct_index": 2, "benchmark_seconds": 30, "explanation": "The slow pointer traverses exactly N/2 elements, completing the search in a single linear pass of O(N) time."},
        {"id": "l2_13", "topic": "Stacks & Queues", "text": "What is the result of attempting to Pop from an empty stack?", "options": ["Stack Overflow", "Stack Underflow", "Division by zero", "Memory fragmentation"], "correct_index": 1, "benchmark_seconds": 20, "explanation": "Popping from an empty stack triggers a Stack Underflow error."},
        {"id": "l2_14", "topic": "Cache Optimization", "text": "To support fast linear cache lookups, why are arrays often faster than linked lists in hardware?", "options": ["Array nodes are larger", "Spatial locality - contiguous elements reside in CPU caches", "Linked lists use more pointers", "Arrays have dynamic bounds"], "correct_index": 1, "benchmark_seconds": 35, "explanation": "Contiguous array elements reside in cache lines. Accessing them triggers prefetching, which avoids CPU cache misses."},
        {"id": "l2_15", "topic": "Linked Lists", "text": "In a singly linked list, what does the tail node's next pointer reference?", "options": ["Head node", "Null / None", "Self node", "Arbitrary node"], "correct_index": 1, "benchmark_seconds": 15, "explanation": "The terminal tail node of a singly linked list points to Null/None, marking the end of traversal."}
    ],
    3: [ # Level 3: Search & Logic (Sorting, Searching & Basic Logic)
        {"id": "l3_01", "topic": "Binary Search", "text": "What is the worst-case search complexity of Binary Search on a sorted array of size N?", "options": ["O(1)", "O(log N) - halving intervals", "O(N)", "O(N log N)"], "correct_index": 1, "benchmark_seconds": 30, "explanation": "Binary search divides the search space in half at each iteration, resulting in O(log N) runtime."},
        {"id": "l3_02", "topic": "Sorting & Searching", "text": "Which sorting algorithm has a worst-case complexity of O(N^2) but is extremely efficient for small datasets or mostly sorted lists?", "options": ["Merge Sort", "Quick Sort", "Insertion Sort", "Heap Sort"], "correct_index": 2, "benchmark_seconds": 30, "explanation": "Insertion sort runs in O(N^2) worst case but evaluates in O(N) linear time for sorted arrays, beating complex algorithms on small inputs."},
        {"id": "l3_03", "topic": "Bitwise Operations", "text": "What is the bitwise equivalent of multiplying an integer by 2?", "options": ["Bitwise AND by 2", "Right shift by 1 bit (>> 1)", "Left shift by 1 bit (<< 1)", "Bitwise XOR by 2"], "correct_index": 2, "benchmark_seconds": 25, "explanation": "Shifting binary representation left by 1 bit (e.g. 0101 -> 1010) multiplies the numerical value by 2."},
        {"id": "l3_04", "topic": "Sorting & Searching", "text": "Which sorting algorithm is stable and guarantees O(N log N) worst-case time complexity?", "options": ["Quick Sort", "Selection Sort", "Merge Sort - preserves element ordering", "Bubble Sort"], "correct_index": 2, "benchmark_seconds": 35, "explanation": "Merge sort divides arrays and merges stably, maintaining relative order of equal keys in all scenarios in O(N log N) time."},
        {"id": "l3_05", "topic": "Basic Logic", "text": "Which search algorithm is optimal to scan an unsorted set?", "options": ["Binary Search", "Linear Search - check elements one-by-one", "Interpolation Search", "Exponential Search"], "correct_index": 1, "benchmark_seconds": 20, "explanation": "Without sorting order, there are no structural shortcuts, requiring a linear O(N) scan."},
        {"id": "l3_06", "topic": "Binary Search", "text": "In a sorted array with duplicates, which Binary Search variant finds the first occurrence of a target?", "options": ["Standard search", "Lower Bound Binary Search - checking left boundary matches", "Upper Bound Binary Search", "Linear scan search"], "correct_index": 1, "benchmark_seconds": 35, "explanation": "Lower bound search continues shrinking high boundary constraints even when a match is found, settling on the first occurrence index."},
        {"id": "l3_07", "topic": "Bitwise Operations", "text": "What does the expression `X ^ X` evaluate to?", "options": ["0", "X", "1", "2X"], "correct_index": 0, "benchmark_seconds": 15, "explanation": "XORing any value with itself compares identical bits, resolving to exactly 0."},
        {"id": "l3_08", "topic": "Sorting & Searching", "text": "What is the average runtime complexity of Quick Sort?", "options": ["O(log N)", "O(N)", "O(N log N)", "O(N^2)"], "correct_index": 2, "benchmark_seconds": 25, "explanation": "On average, pivot selection splits arrays evenly, yielding the O(N log N) runtime characteristic."},
        {"id": "l3_09", "topic": "Basic Logic", "text": "Which sorting algorithm repeatedly selects the minimum value from the unsorted segment and swaps it to the front?", "options": ["Insertion Sort", "Selection Sort", "Quick Sort", "Radix Sort"], "correct_index": 1, "benchmark_seconds": 25, "explanation": "Selection sort scans the unsorted subset, identifies the minimum element, and places it at the sorted boundary index."},
        {"id": "l3_10", "topic": "Bitwise Operations", "text": "Which bitwise operator flips all the bits of an integer?", "options": ["Bitwise AND (&)", "Bitwise NOT (~)", "Bitwise OR (|)", "Bitwise XOR (^)"], "correct_index": 1, "benchmark_seconds": 20, "explanation": "Bitwise NOT (~) acts as a complement operator, flipping 0s to 1s and 1s to 0s."},
        {"id": "l3_11", "topic": "Sorting & Searching", "text": "Which sorting algorithm sorts elements digit-by-digit from least significant to most significant?", "options": ["Heap Sort", "Merge Sort", "Radix Sort - linear sorting", "Quick Sort"], "correct_index": 2, "benchmark_seconds": 35, "explanation": "Radix sort groups elements by individual digits, sorting them via stable bucket sorting algorithms in O(D * (N + K)) time."},
        {"id": "l3_12", "topic": "Binary Search", "text": "What is the time complexity of searching in a sorted 2D matrix of size N x M using step-wise elimination starting at the top-right corner?", "options": ["O(log(N*M))", "O(N + M)", "O(N * M)", "O(N^2)"], "correct_index": 1, "benchmark_seconds": 40, "explanation": "At each step, we eliminate either a row or a column, restricting total step operations to O(N + M)."},
        {"id": "l3_13", "topic": "Bitwise Operations", "text": "What is the bitwise equivalent of dividing a positive integer by 2?", "options": ["Left shift (<< 1)", "Right shift (>> 1)", "Complement operator (~)", "Modulo 2"], "correct_index": 1, "benchmark_seconds": 20, "explanation": "Right shifting bits of a positive integer moves all values rightward, effectively dividing it by 2."},
        {"id": "l3_14", "topic": "Sorting & Searching", "text": "Which sorting algorithm operates in-place and guarantees O(N log N) worst-case time complexity?", "options": ["Merge Sort", "Quick Sort", "Heap Sort - uses binary max-heap in-place", "Selection Sort"], "correct_index": 2, "benchmark_seconds": 40, "explanation": "Heap sort utilizes a binary heap structures in-place inside the array, guaranteeing O(N log N) runtime without extra storage allocation."},
        {"id": "l3_15", "topic": "Basic Logic", "text": "If you sort a dataset of 1 million elements that are already fully sorted, which algorithm takes the longest time if pivot selection targets the first element?", "options": ["Merge Sort", "Quick Sort - degrades to O(N^2) unbalanced branches", "Heap Sort", "Insertion Sort"], "correct_index": 1, "benchmark_seconds": 35, "explanation": "Choosing the first element as the pivot on a sorted list splits the recursion into extremely unbalanced branches of size 0 and N-1, causing Quick Sort to degrade to O(N^2) time."}
    ],
    4: [ # Level 4: Hierarchical (Binary Trees, BSTs & Hashing)
        {"id": "l4_01", "topic": "Trees", "text": "What is the height of a balanced binary search tree of size N?", "options": ["O(1)", "O(log N)", "O(N)", "O(N^2)"], "correct_index": 1, "benchmark_seconds": 30, "explanation": "Balanced trees split nodes symmetrically, keeping depth limited to O(log N)."},
        {"id": "l4_02", "topic": "BSTs", "text": "In a valid Binary Search Tree (BST), what is the key relationship of a node relative to its children?", "options": ["Node key is larger than left child and smaller than right child", "Node key is smaller than left child and larger than right child", "Node key is equal to both children", "No ordering invariants"], "correct_index": 0, "benchmark_seconds": 25, "explanation": "By definition, a BST enforces left-subtree keys < root key < right-subtree keys."},
        {"id": "l4_03", "topic": "Hashing", "text": "What is the average lookup time of a key in a well-distributed hash map?", "options": ["O(1)", "O(log N)", "O(N)", "O(N log N)"], "correct_index": 0, "benchmark_seconds": 20, "explanation": "Constant O(1) average lookup is achieved when keys map uniformly across bucket indices."},
        {"id": "l4_04", "topic": "Trees", "text": "Which tree traversal processes child nodes fully before visiting parent nodes?", "options": ["Preorder", "Inorder", "Postorder - left, right, root", "Level-order"], "correct_index": 2, "benchmark_seconds": 30, "explanation": "Postorder traversal visits child subtrees first, then processes the parent root node."},
        {"id": "l4_05", "topic": "BSTs", "text": "What is the time complexity to locate the minimum element in a BST of size N?", "options": ["O(1)", "O(log N) on average - walking leftwards", "O(N)", "O(N log N)"], "correct_index": 1, "benchmark_seconds": 25, "explanation": "The minimum element lies at the leftmost node. Traversing down left paths takes logarithmic O(log N) average time."},
        {"id": "l4_06", "topic": "Hashing", "text": "What does a high 'load factor' indicate in a hash map?", "options": ["Too many collisions likely - buckets mostly filled", "Hash keys are too small", "Memory allocations are underutilized", "Search algorithms are fast"], "correct_index": 0, "benchmark_seconds": 30, "explanation": "Load factor is ratio of items to buckets. High ratio indicates full buckets, increasing collisions."},
        {"id": "l4_07", "topic": "Trees", "text": "Which tree traversal uses a FIFO queue to visit nodes level-by-level?", "options": ["Preorder", "Inorder", "Postorder", "Level-order / BFS"], "correct_index": 3, "benchmark_seconds": 25, "explanation": "Level-order traversal uses a Queue to process nodes level-by-level starting from the root node."},
        {"id": "l4_08", "topic": "BSTs", "text": "What is the worst-case search complexity of a BST if elements were inserted in sorted order?", "options": ["O(1)", "O(log N)", "O(N) - degenerates to a single linked line", "O(N^2)"], "correct_index": 2, "benchmark_seconds": 35, "explanation": "Sorted inserts create a fully skewed tree (a single branch), degrading lookup searches to linear O(N) time."},
        {"id": "l4_09", "topic": "Hashing", "text": "Which probing strategy checks buckets at indices `(hash + i*i) % size`?", "options": ["Linear Probing", "Quadratic Probing", "Double Hashing", "Separate Chaining"], "correct_index": 1, "benchmark_seconds": 30, "explanation": "Quadratic probing increments alternative search step indices quadratically (i squared) to locate free slots."},
        {"id": "l4_10", "topic": "Trees", "text": "In a complete binary tree of depth D, how many leaf nodes are present at the bottom level if fully populated?", "options": ["2^D", "2^(D-1)", "D^2", "2D"], "correct_index": 0, "benchmark_seconds": 30, "explanation": "A complete binary tree doubles leaf nodes at each level, leaving exactly 2^D leaf nodes at depth D (starting level 0 root)."},
        {"id": "l4_11", "topic": "BSTs", "text": "What is the successor of a node in a BST inorder traversal if the node has a right child?", "options": ["Parent node", "Leftmost child of the right subtree", "Rightmost child of the left subtree", "Root node"], "correct_index": 1, "benchmark_seconds": 35, "explanation": "The successor is the next larger value, which resides at the leftmost node in the right child's subtree."},
        {"id": "l4_12", "topic": "Hashing", "text": "What is a major advantage of open addressing over separate chaining in cache performance?", "options": ["Fewer total collisions", "Contiguous storage in memory, improving cache locality", "Wider key space support", "Easier deletion algorithms"], "correct_index": 1, "benchmark_seconds": 35, "explanation": "Open addressing maps colliding items inside the table array itself, improving CPU cache alignment by keeping lookups contiguous."},
        {"id": "l4_13", "topic": "Trees", "text": "How many null children pointers are present in a binary tree of size N?", "options": ["N", "N + 1 - child branches boundary links", "2N", "N / 2"], "correct_index": 1, "benchmark_seconds": 35, "explanation": "A binary tree of size N has 2N total child slots. Exactly N-1 are active parent links, leaving N+1 null pointer leaf ends."},
        {"id": "l4_14", "topic": "BSTs", "text": "Which self-balancing binary search tree uses color properties (Red/Black) to maintain a maximum height balance ratio of less than 2?", "options": ["AVL Tree", "Red-Black Tree", "Splay Tree", "B-Tree"], "correct_index": 1, "benchmark_seconds": 40, "explanation": "Red-Black trees store node colors and trigger balance updates to ensure the longest root-to-leaf path is at most twice the shortest path length."},
        {"id": "l4_15", "topic": "Trees", "text": "What is the time complexity to check if two binary trees are identical in structures and values recursively?", "options": ["O(log N)", "O(N) - visiting all nodes", "O(N^2)", "O(2^N)"], "correct_index": 1, "benchmark_seconds": 30, "explanation": "Comparing structures requires exploring both trees completely, checking N nodes in linear O(N) time."}
    ],
    5: [ # Level 5: Relational & Scheduling (Graphs, Heaps & Priority Queues)
        {"id": "l5_01", "topic": "Graphs", "text": "What is the time complexity of Breadth-First Search (BFS) on a graph represented as an adjacency list with V vertices and E edges?", "options": ["O(V)", "O(E)", "O(V + E) - checking all vertices and adjacent edges", "O(V * E)"], "correct_index": 2, "benchmark_seconds": 35, "explanation": "BFS explores all vertices and scans their corresponding adjacent edge lists, taking linear O(V + E) time."},
        {"id": "l5_02", "topic": "Heaps", "text": "What is the time complexity to insert a new element into a binary heap of size N?", "options": ["O(1)", "O(log N) - bubble-up element adjustments", "O(N)", "O(N log N)"], "correct_index": 1, "benchmark_seconds": 30, "explanation": "Inserting places the item at the heap end and bubbles it up vertically to preserve heap order, taking O(log N) max operations."},
        {"id": "l5_03", "topic": "Greedy", "text": "In a standard Minimum Spanning Tree (MST) problem, which greedy algorithm grows the tree node-by-node, adding the cheapest adjacent vertex?", "options": ["Kruskal's Algorithm", "Prim's Algorithm - vertex expansion focus", "Dijkstra's Algorithm", "Bellman-Ford"], "correct_index": 1, "benchmark_seconds": 35, "explanation": "Prim's algorithm starts from a single vertex and greedily inserts the closest unvisited node adjacent to the active tree."},
        {"id": "l5_04", "topic": "Graphs", "text": "Which algorithm is optimal to detect negative weight cycles in a directed graph?", "options": ["Dijkstra's Algorithm", "Bellman-Ford Algorithm - supports negative edge checks", "Kruskal's Algorithm", "Depth First Search"], "correct_index": 1, "benchmark_seconds": 45, "explanation": "Bellman-Ford loops V-1 times. A V-th iteration checking for capacity updates indicates a negative cycle."},
        {"id": "l5_05", "topic": "Heaps", "text": "What is the time complexity to build a binary heap from an unsorted array of size N in-place using Floyd's heapify method?", "options": ["O(1)", "O(N) - linear heap assembly", "O(N log N)", "O(N^2)"], "correct_index": 1, "benchmark_seconds": 40, "explanation": "Floyd's heapify method sifts down elements starting from internal parents, summing to a linear O(N) time complexity."},
        {"id": "l5_06", "topic": "Greedy", "text": "What is a primary characteristic of a Greedy Choice Property?", "options": ["We make the locally optimal choice hoping for a globally optimal result", "We check all subproblems iteratively", "We reverse previous decisions if conflicts arise", "We evaluate probability indices"], "correct_index": 0, "benchmark_seconds": 25, "explanation": "Greedy algorithms make immediate, local optimizations without evaluating future state consequences, assuming a global solution emerges."},
        {"id": "l5_07", "topic": "Graphs", "text": "What is the topological sort ordering of a directed graph containing cycles?", "options": ["Unsorted linear list", "Topological sorting is impossible on cyclic graphs", "Sorted list ignoring cycle links", "Self-balanced list"], "correct_index": 1, "benchmark_seconds": 30, "explanation": "Topological sort requires directed acyclic graphs (DAGs). Cycles prevent ordering nodes since dependency paths loop indefinitely."},
        {"id": "l5_08", "topic": "Heaps", "text": "What is the worst-case time complexity of extracting the minimum element from a Min-Heap?", "options": ["O(1)", "O(log N) - sifting down replacement root", "O(N)", "O(N log N)"], "correct_index": 1, "benchmark_seconds": 30, "explanation": "Evicting the root swaps it with the heap end. Sifting this element down to restore min-heap properties takes O(log N) time."},
        {"id": "l5_09", "topic": "Greedy", "text": "Which algorithm finds the MST of a graph by sorting all edges by weight and adding them one-by-one, skipping those that form cycles?", "options": ["Prim's Algorithm", "Kruskal's Algorithm - edge sorting focus", "Dijkstra's Algorithm", "Bellman-Ford"], "correct_index": 1, "benchmark_seconds": 35, "explanation": "Kruskal's algorithm sorts all edges and uses Disjoint Set Union (DSU) to stably link forests without cyclic dependencies."},
        {"id": "l5_10", "topic": "Graphs", "text": "What is the space complexity of representing a sparse graph with V vertices and E edges as an adjacency matrix?", "options": ["O(V)", "O(V + E)", "O(V^2) - allocating full grid dimensions", "O(V * E)"], "correct_index": 2, "benchmark_seconds": 30, "explanation": "An adjacency matrix allocates a V x V grid, consuming O(V^2) space regardless of how few edges are present."},
        {"id": "l5_11", "topic": "Heaps", "text": "What is the time complexity to retrieve (just look up) the maximum element in a Max-Heap?", "options": ["O(1) - lies directly at the root node", "O(log N)", "O(N)", "O(N log N)"], "correct_index": 0, "benchmark_seconds": 15, "explanation": "In a Max-Heap, the largest value always resides at the root index 0, enabling O(1) constant time retrieval."},
        {"id": "l5_12", "topic": "Greedy", "text": "Does a greedy algorithm for the Fractional Knapsack problem guarantee an optimal solution?", "options": ["Yes - sorting items by value-to-weight ratio", "No - it only provides approximations", "Only if weights are equal", "Only if capacity is infinite"], "correct_index": 0, "benchmark_seconds": 35, "explanation": "By sorting elements by density ratio (value/weight) and taking fractional segments, the greedy approach achieves the maximum possible value."},
        {"id": "l5_13", "topic": "Graphs", "text": "What is the maximum number of edges in a simple undirected graph with V vertices?", "options": ["V", "V * (V - 1) / 2", "V^2", "2V"], "correct_index": 1, "benchmark_seconds": 30, "explanation": "Every vertex can link to all other V-1 vertices. Dividing by 2 removes duplicate undirected links, giving V*(V-1)/2 total edges."},
        {"id": "l5_14", "topic": "Heaps", "text": "Which data structure is optimal to implement a dynamic Priority Queue?", "options": ["Array", "Linked List", "Binary Heap - provides fast log(N) insertion and extraction", "BST"], "correct_index": 2, "benchmark_seconds": 25, "explanation": "Binary heaps support fast insertions and priority deletions in O(log N) time, making them optimal for priority queues."},
        {"id": "l5_15", "topic": "Graphs", "text": "Which algorithm resolves single-source shortest paths on weighted graphs with non-negative edge weights in O((V + E) log V) time?", "options": ["Dijkstra's Algorithm", "Bellman-Ford", "Floyd-Warshall", "Topological search"], "correct_index": 0, "benchmark_seconds": 35, "explanation": "Dijkstra's algorithm uses a priority queue to explore closest vertices, guaranteeing shortest paths on positive graphs in O(E log V) time."}
    ],
    6: [ # Level 6: Complex Optimizations (Dynamic Programming & Tries)
        {"id": "l6_01", "topic": "Dynamic Programming", "text": "What is the primary technical identifier of a Dynamic Programming problem?", "options": ["Overlapping subproblems and optimal substructure", "Greedy choice properties", "Direct sorting interfaces", "LIFO execution loops"], "correct_index": 0, "benchmark_seconds": 35, "explanation": "DP stores solved subproblems (overlapping) and builds the global solution from them (optimal substructure)."},
        {"id": "l6_02", "topic": "Segment Trees", "text": "What is the time complexity of querying a range minimum in a Segment Tree of size N?", "options": ["O(1)", "O(log N) - traversing tree segments", "O(N)", "O(N log N)"], "correct_index": 1, "benchmark_seconds": 40, "explanation": "A Segment Tree stores ranges in a balanced tree format, restricting range queries to O(log N) steps."},
        {"id": "l6_03", "topic": "Tries", "text": "What is the lookup time complexity to search for a word of length L in a Trie containing N words?", "options": ["O(L) - traversing character links", "O(log N)", "O(N)", "O(N * L)"], "correct_index": 0, "benchmark_seconds": 35, "explanation": "Tries traverse character nodes one-by-one. Searching takes O(L) steps, entirely independent of the total word count N."},
        {"id": "l6_04", "topic": "Dynamic Programming", "text": "Which DP approach resolves states iteratively by filling up a multidimensional array starting from base cases?", "options": ["Memoization", "Tabulation - bottom-up iterative calculation", "Greedy scanning", "Recursion tree"], "correct_index": 1, "benchmark_seconds": 35, "explanation": "Tabulation (bottom-up) loops iteratively, filling a table state-by-state from base cases up to the target."},
        {"id": "l6_05", "topic": "Segment Trees", "text": "How much memory space is allocated to build a Segment Tree for an array of size N using a standard array representation?", "options": ["O(N)", "O(4N) - standard size boundaries allocating safety bounds", "O(N^2)", "O(2^N)"], "correct_index": 1, "benchmark_seconds": 40, "explanation": "An array representation of a segment tree requires at most 4N size allocation to hold all parent and leaf split nodes safely."},
        {"id": "l6_06", "topic": "Tries", "text": "What is the child nodes storage capacity typically allocated to each node in a standard alphabet Trie (lowercase a-z)?", "options": ["2 pointer references", "26 pointer references - direct lowercase letter indices", "Variable linked lists", "Dynamic heaps"], "correct_index": 1, "benchmark_seconds": 30, "explanation": "Alphabet tries allocate a size-26 pointer array at each node to map letters 'a' through 'z' directly in O(1) time."},
        {"id": "l6_07", "topic": "Dynamic Programming", "text": "What is the time complexity of the standard 0/1 Knapsack problem using dynamic programming with N items and Knapsack capacity W?", "options": ["O(2^N)", "O(N * W) - pseudo-polynomial runtime table", "O(N + W)", "O(N^2)"], "correct_index": 1, "benchmark_seconds": 45, "explanation": "The DP table holds size N x W. Filling each state takes constant O(1) time, yielding O(N * W) runtime."},
        {"id": "l6_08", "topic": "Segment Trees", "text": "What is the time complexity to update a single value in a Fenwick Tree (Binary Indexed Tree) of size N?", "options": ["O(1)", "O(log N) - traversing set bit offsets", "O(N)", "O(N log N)"], "correct_index": 1, "benchmark_seconds": 35, "explanation": "Fenwick trees propagate updates along indices using bitwise least-significant-bit operations, taking O(log N) time."},
        {"id": "l6_09", "topic": "Tries", "text": "Why are Tries optimal for prefix matching over Hash Tables?", "options": ["They take less total memory", "They traverse word prefixes in a single linear character path, locating all suffix options", "They avoid collisions", "They support floating point indices"], "correct_index": 1, "benchmark_seconds": 35, "explanation": "Hash tables require rehashing and full matching. Tries share prefix paths, letting you scan a prefix once and easily retrieve all matching suffixes."},
        {"id": "l6_10", "topic": "Dynamic Programming", "text": "What is the primary memory disadvantage of standard Top-Down Memoization compared to Space-Optimized Tabulation?", "options": ["Worse time complexity", "Stack Overflow risks and recursion memory overhead", "Poor lookup speed", "Table size resizing"], "correct_index": 1, "benchmark_seconds": 35, "explanation": "Top-down DP uses recursion. This carries call-stack overhead and risks Stack Overflow for deep state spaces, whereas tabulation is purely iterative."},
        {"id": "l6_11", "topic": "Segment Trees", "text": "Which operation is NOT typically supported in O(log N) time by a standard Segment Tree?", "options": ["Range sum query", "Range minimum query", "Sorting the complete range in-place", "Point update"], "correct_index": 2, "benchmark_seconds": 35, "explanation": "Segment trees query and update ranges in O(log N) time, but sorting requires a complete restructure taking O(N log N) time."},
        {"id": "l6_12", "topic": "Tries", "text": "In a suffix tree (a specialized Trie variation), how is the text represented?", "options": ["Prefix strings only", "All possible suffixes of a text are stored, allowing immediate substring searches", "Encrypted hashes", "Reversed text words"], "correct_index": 1, "benchmark_seconds": 40, "explanation": "Storing all suffixes of a text in a suffix tree facilitates substring and pattern matching searches in linear time relative to pattern length."},
        {"id": "l6_13", "topic": "Dynamic Programming", "text": "What is the runtime complexity of the Longest Common Subsequence (LCS) problem for two strings of size N and M using DP?", "options": ["O(N + M)", "O(N * M) - filling the grid matrices", "O(2^(N+M))", "O(log(N*M))"], "correct_index": 1, "benchmark_seconds": 40, "explanation": "LCS builds a 2D state matrix of size N x M. Filling this matrix iteratively takes O(N * M) time."},
        {"id": "l6_14", "topic": "Segment Trees", "text": "What is the time complexity to construct a Segment Tree from an array of size N?", "options": ["O(log N)", "O(N) - recursively building bottom-up child sums", "O(N log N)", "O(N^2)"], "correct_index": 1, "benchmark_seconds": 40, "explanation": "Constructing visits each parent and leaf node exactly once in a balanced tree of size 4N, taking linear O(N) time."},
        {"id": "l6_15", "topic": "Dynamic Programming", "text": "In DP, what does the 'Matrix Chain Multiplication' algorithm optimize?", "options": ["Matrix values product operations", "The order of parenthesization to minimize scalar multiplication operations", "Memory space layout matrices", "Parallel computing blocks"], "correct_index": 1, "benchmark_seconds": 45, "explanation": "Matrix chain multiplication is associative. Matrix Chain Multiplication optimization uses dynamic programming to select the ordering of pairs that minimizes costly scalar products."}
    ]
}

# Algorithmic Coding Challenges mapped to specific levels to run dynamic execution
CODING_DATA = {
    1: [
        {
            "id": "l1_c01",
            "topic": "Arrays",
            "text": "Write a function 'productExceptSelf(nums)' that takes an array of integers and returns a new array where each element at index i is the product of all elements except nums[i]. Implement this in O(N) time without using the division operator.",
            "type": "coding",
            "starter_code": {
                "python": "def productExceptSelf(nums: list[int]) -> list[int]:\n    # Write your Python code here\n    n = len(nums)\n    res = [1] * n\n    # Calculate prefix and suffix products...\n    return res",
                "javascript": "function productExceptSelf(nums) {\n    // Write your JavaScript code here\n    const n = nums.length;\n    const res = new Array(n).fill(1);\n    return res;\n}",
                "cpp": "vector<int> productExceptSelf(vector<int>& nums) {\n    // Write your C++ code here\n    int n = nums.size();\n    vector<int> res(n, 1);\n    return res;\n}"
            },
            "correct_keyword": "for",
            "benchmark_seconds": 120,
            "explanation": "Compute prefix products in a forward sweep and accumulate suffix products in a backward sweep."
        }
    ],
    2: [
        {
            "id": "l2_c01",
            "topic": "Linked Lists",
            "text": "Write a function 'reverseList(head)' to reverse a singly linked list iteratively and return the new head pointer. Assume typical ListNode node mapping holding value and next reference.",
            "type": "coding",
            "starter_code": {
                "python": "def reverseList(head):\n    # Write your iterative pointer swap code here\n    prev = None\n    curr = head\n    return prev",
                "javascript": "function reverseList(head) {\n    // Write your iterative pointer swap code here\n    let prev = null;\n    let curr = head;\n    return prev;\n}",
                "cpp": "ListNode* reverseList(ListNode* head) {\n    // Write your C++ code here\n    ListNode* prev = nullptr;\n    ListNode* curr = head;\n    return prev;\n}"
            },
            "correct_keyword": "curr",
            "benchmark_seconds": 110,
            "explanation": "Iteratively shift pointers using three pointers: prev, curr, and next_node to reverse traversal order safely."
        }
    ],
    3: [
        {
            "id": "l3_c01",
            "topic": "Binary Search",
            "text": "Write a function 'searchInsert(nums, target)' that receives a sorted array of distinct integers and a target. Return index if found, else return index where it would reside if inserted in sorted order (O(log N) constraint).",
            "type": "coding",
            "starter_code": {
                "python": "def searchInsert(nums: list[int], target: int) -> int:\n    # Write your binary search log(N) code here\n    low, high = 0, len(nums) - 1\n    return low",
                "javascript": "function searchInsert(nums, target) {\n    // Write your binary search log(N) code here\n    let low = 0, high = nums.length - 1;\n    return low;\n}",
                "cpp": "int searchInsert(vector<int>& nums, int target) {\n    // Write your C++ code here\n    int low = 0, high = nums.size() - 1;\n    return low;\n}"
            },
            "correct_keyword": "mid",
            "benchmark_seconds": 90,
            "explanation": "Use standard binary search checking mid index. Shrink boundaries until low pointer passes high to locate insertion position."
        }
    ],
    4: [
        {
            "id": "l4_c01",
            "topic": "Trees",
            "text": "Write a function 'maxDepth(root)' to calculate the maximum depth / height of a binary tree. A tree's maximum depth is the count of nodes along the longest path from root down to deepest leaf node.",
            "type": "coding",
            "starter_code": {
                "python": "def maxDepth(root) -> int:\n    # Write your recursive tree traversal here\n    if not root: return 0\n    return 1",
                "javascript": "function maxDepth(root) {\n    // Write your recursive tree traversal here\n    if (!root) return 0;\n    return 1;\n}",
                "cpp": "int maxDepth(TreeNode* root) {\n    // Write your C++ code here\n    if (!root) return 0;\n    return 1;\n}"
            },
            "correct_keyword": "max",
            "benchmark_seconds": 100,
            "explanation": "Recursively compute depth of left and right child nodes, returning max(left_depth, right_depth) + 1."
        }
    ],
    5: [
        {
            "id": "l5_c01",
            "topic": "Heaps",
            "text": "Write a function 'findKthLargest(nums, k)' to isolate and return the K-th largest element in an unsorted integer list. Optimally use heap structures or quickselect logic.",
            "type": "coding",
            "starter_code": {
                "python": "def findKthLargest(nums: list[int], k: int) -> int:\n    # Write your quickselect or min-heap logic here\n    nums.sort()\n    return nums[-k]",
                "javascript": "function findKthLargest(nums, k) {\n    // Write your quickselect or min-heap logic here\n    nums.sort((a,b) => a-b);\n    return nums[nums.length - k];\n}",
                "cpp": "int findKthLargest(vector<int>& nums, int k) {\n    // Write your C++ code here\n    sort(nums.begin(), nums.end());\n    return nums[nums.size() - k];\n}"
            },
            "correct_keyword": "sort",
            "benchmark_seconds": 120,
            "explanation": "Using sorting guarantees O(N log N). Using a Min-Heap of size K provides an optimal O(N log K) performance limit."
        }
    ],
    6: [
        {
            "id": "l6_c01",
            "topic": "Dynamic Programming",
            "text": "Write an optimal function 'maxSubArray(nums)' that identifies the contiguous subarray within a one-dimensional integer list which has the largest sum, returning the sum value (Kadane's Algorithm).",
            "type": "coding",
            "starter_code": {
                "python": "def maxSubArray(nums: list[int]) -> int:\n    # Write your Kadane's optimal dynamic programming scan here\n    max_sum = nums[0]\n    curr_sum = nums[0]\n    return max_sum",
                "javascript": "function maxSubArray(nums) {\n    // Write your Kadane's optimal dynamic programming scan here\n    let max_sum = nums[0];\n    let curr_sum = nums[0];\n    return max_sum;\n}",
                "cpp": "int maxSubArray(vector<int>& nums) {\n    // Write your C++ code here\n    int max_sum = nums[0];\n    int curr_sum = nums[0];\n    return max_sum;\n}"
            },
            "correct_keyword": "max",
            "benchmark_seconds": 120,
            "explanation": "Maintain max contiguous sum at current position, adding to previous sum or resetting to current value."
        }
    ]
}

# Post-Process to combine all questions and ensure types are set
ARENA_QUESTIONS = {}

for lvl in range(1, 7):
    ARENA_QUESTIONS[lvl] = []
    
    # 1. Add MCQ questions with explicit 'type' tag
    for q in MCQ_DATA[lvl]:
        q_copy = dict(q)
        q_copy["type"] = "mcq"
        ARENA_QUESTIONS[lvl].append(q_copy)
        
    # 2. Add high-value Algorithmic coding questions
    for q in CODING_DATA[lvl]:
        q_copy = dict(q)
        q_copy["type"] = "coding"
        ARENA_QUESTIONS[lvl].append(q_copy)
